sudo: required
cache:
  - apt
language: generic

matrix:
  include:
  - name: "Focal noetic"
    dist: focal
    env: ROS_DISTRO=noetic

env:
  global:
    - ROS_CI_DESKTOP="`lsb_release -cs`"
    - CI_SOURCE_PATH=$(pwd)
    - ROS_PARALLEL_JOBS='-j8 -l6'

# Install system dependencies.
before_install:
  - sudo sh -c "echo \"deb http://packages.ros.org/ros/ubuntu $ROS_CI_DESKTOP main\" > /etc/apt/sources.list.d/ros-latest.list"
  - sudo apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
  - sudo apt-get update -qq
  - sudo apt-get install -y python3-catkin-pkg python3-rosdep ros-$ROS_DISTRO-desktop-full
  - source /opt/ros/$ROS_DISTRO/setup.bash

  - sudo rosdep init
  - rosdep update --include-eol-distros

  # - sudo apt-get install -y python3-pip
  # - python3 -m pip install pynput

# Create a catkin workspace with the package under integration.
install:
  - mkdir -p ~/catkin_ws/src
  - cd ~/catkin_ws/src
  - catkin_init_workspace
  - cd ~/catkin_ws
  - catkin_make
  - source devel/setup.bash
  - cd ~/catkin_ws/src
  - ln -s $CI_SOURCE_PATH .

# Install package dependencies.
before_script:
  - cd ~/catkin_ws
  - rosdep install -y --from-paths src --ignore-src --rosdistro $ROS_DISTRO

# Compile.
script:
  - source /opt/ros/$ROS_DISTRO/setup.bash
  - cd ~/catkin_ws
  - catkin_make
  - source devel/setup.bash
  - catkin_make run_tests -j1 && catkin_test_results